# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-07-15T09:23:37+00:00

from __future__ import annotations

from pydantic import BaseModel


class Parameter(BaseModel):
    key: str
    value: str


class Filelist(BaseModel):
    key: str
    files: list[str]


class Commandfile(BaseModel):
    parameters: list[Parameter]
    inputs: list[Filelist]
    outputs: list[Filelist]
